print("How old are you?", end=' ')
age = input()
print("How tall are you?", end=' ')
height = input()
print("How much do you weigh?", end=' ')
weight = input()
print("Give a number", end=' ')
num = int(input())
num = num*2
print(f"{num*2}")
print(f"So, you're {age} old, {height} tall and {weight} heavy.")
